// Builds dist/registry.json (ScriptletRegistryJSON) and dist/registry.js. Workstream T3.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { redirectResources, registry, registryJSON, serializeScriptletFn } from '../src/index';
import { generateResources } from './gen-resources';

const here = dirname(fileURLToPath(import.meta.url));
const distDir = join(here, '..', 'dist');

function validate(): void {
  const seen = new Map<string, string>();
  for (const def of Object.values(registry)) {
    for (const name of [def.name, ...def.aliases]) {
      const owner = seen.get(name);
      if (owner !== undefined && owner !== def.name) {
        throw new Error(`scriptlets: "${name}" is claimed by both "${owner}" and "${def.name}"`);
      }
      seen.set(name, def.name);
    }
    if (def.args.some((a) => a.name === '')) {
      throw new Error(`scriptlets: "${def.name}" has an unnamed argument`);
    }
  }
}

function buildRegistryModule(): string {
  const entries = Object.values(registry)
    .map(
      (def) =>
        `  ${JSON.stringify(def.name)}: { fn: ${JSON.stringify(serializeScriptletFn(def.fn, def.name))}, trusted: ${def.trusted} },`,
    )
    .join('\n');
  const resources = Object.entries(redirectResources)
    .map(([name, path]) => `  ${JSON.stringify(name)}: ${JSON.stringify(path)},`)
    .join('\n');
  return `// Generated by packages/scriptlets/scripts/build.ts — do not edit.
/** Canonical scriptlet name → serialised MAIN-world function source. */
export const scriptlets = {
${entries}
};

/** $redirect resource name → path under the extension's web-accessible resources. */
export const redirectResources = {
${resources}
};
`;
}

validate();
mkdirSync(distDir, { recursive: true });

const json = `${JSON.stringify(registryJSON(), null, 2)}\n`;
writeFileSync(join(distDir, 'registry.json'), json);

const module = buildRegistryModule();
writeFileSync(join(distDir, 'registry.js'), module);

const resources = generateResources();

const count = Object.keys(registry).length;
console.info(
  `scriptlets: ${count} scriptlets, ${Object.keys(redirectResources).length} redirect names, ` +
    `registry.js ${module.length} bytes, registry.json ${json.length} bytes, ${resources.length} resource files`,
);
